### ISSUE TITLE
Deploy Automation

### ISSUE THREAD

**Issue by takanakahiko** [takanakahiko/slack-emoji-meister#185]
At the moment, deployment is done manually.
However, it will support firefox in the future.
Continuing to deploy chrome and firefox to keep up with updates is hard work.
 
So I want to automate deployment using GitHub Actions.

**Comment by takanakahiko** [comment]
In firefox's case...


```
~/dev/github/slack-emoji-meister master* 6s
❯ npm run deploy:firefox

> slack-emoji-meister@0.3.2 deploy:firefox /Users/takayuki.nakayama/dev/github/slack-emoji-meister
> web-ext-submit --api-key $FIREFOX_ISSUER --api-secret $FIREFOX_SECRET --source-dir dist/firefox --api-url-prefix https://addons.mozilla.org/api/v4

Applying config file: ./package.json
Building web extension from /Users/takayuki.nakayama/dev/github/slack-emoji-meister/dist/firefox
Validating add-on [............................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/27e1a3b6e1184f1db62efd01bcad68cf
Signing add-on [...............................................................]
0
FAIL

o: The extension could not be signed
    at /Users/takayuki.nakayama/dev/github/slack-emoji-meister/node_modules/web-ext/dist/web-ext.js:1:66345
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at E.execute (/Users/takayuki.nakayama/dev/github/slack-emoji-meister/node_modules/web-ext/dist/web-ext.js:1:32886)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slack-emoji-meister@0.3.2 deploy:firefox: `web-ext-submit --api-key $FIREFOX_ISSUER --api-secret $FIREFOX_SECRET --source-dir dist/firefox --api-url-prefix https://addons.mozilla.org/api/v4`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slack-emoji-meister@0.3.2 deploy:firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/takayuki.nakayama/.npm/_logs/2020-03-20T05_59_08_422Z-debug.log
```

An error is displayed, but the deployment was successful. We are looking for a solution to not show the error.
